// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCcYeBf_ARjzVNoxgkvgV4jGvEoSpx0o',
    appId: '1:97011023675:web:1e873b81f82e98c5e5011e',
    messagingSenderId: '97011023675',
    projectId: 'logintrial-2bb93',
    authDomain: 'logintrial-2bb93.firebaseapp.com',
    storageBucket: 'logintrial-2bb93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXMoDvTL4mvVFwwS6x9HO49oxl9xU1CmY',
    appId: '1:97011023675:android:ed563221c6d7421ee5011e',
    messagingSenderId: '97011023675',
    projectId: 'logintrial-2bb93',
    storageBucket: 'logintrial-2bb93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAalsCVbyMTHDaUfTM0s-9L8i1ma24nmwg',
    appId: '1:97011023675:ios:f75277713732baf9e5011e',
    messagingSenderId: '97011023675',
    projectId: 'logintrial-2bb93',
    storageBucket: 'logintrial-2bb93.appspot.com',
    androidClientId: '97011023675-tfqrtrn9fpb5ntjkjie3ebtnobvg3nqt.apps.googleusercontent.com',
    iosClientId: '97011023675-agse6dab7m1slnn4tqmvvuj3p1g63epn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loggingg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAalsCVbyMTHDaUfTM0s-9L8i1ma24nmwg',
    appId: '1:97011023675:ios:f75277713732baf9e5011e',
    messagingSenderId: '97011023675',
    projectId: 'logintrial-2bb93',
    storageBucket: 'logintrial-2bb93.appspot.com',
    androidClientId: '97011023675-tfqrtrn9fpb5ntjkjie3ebtnobvg3nqt.apps.googleusercontent.com',
    iosClientId: '97011023675-agse6dab7m1slnn4tqmvvuj3p1g63epn.apps.googleusercontent.com',
    iosBundleId: 'com.example.loggingg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiCcYeBf_ARjzVNoxgkvgV4jGvEoSpx0o',
    appId: '1:97011023675:web:2055f5a29db4d880e5011e',
    messagingSenderId: '97011023675',
    projectId: 'logintrial-2bb93',
    authDomain: 'logintrial-2bb93.firebaseapp.com',
    storageBucket: 'logintrial-2bb93.appspot.com',
  );
}
